### ISSUE TITLE
Add help for installing transformation advisor

### ISSUE THREAD

**Issue by paulbarr** [IBM/app-mod-journey#61]
Currently we don't provide any information about installing TA
The options are either
 - we add a node at the start for isntalling and show the options
 - we add a QUickStart or Install section in the header

The isntall options are
 - OCP
 - non-OCP
 - Techzone (IBM only)
 - Fyre (IBM only)

@barnsie007 @transformationAdvisor-sdk Thoughts?

**Comment by barnsie007** [comment]
think the option in the header is best - majority of people who get to the playbook page will probably have TA already installed, so not sure if having an extra node would be worthwhile

**Comment by transformationAdvisor-sdk** [comment]
Agree,  add the install section in the header is better,  the whole playbook is talking about how to use TA.

**Comment by paulbarr** [comment]
Added 'Install' option to the header
